Linux build
QutEcoacoustics/ap-desktop pull request #27
Opened 2019-05-02 01:08 UTC by Allcharles

Added ability for `npm run make` command to build both linux (.deb) and windows (.exe) files and installers. Program does not yet have icons, but they have been added to a res folder. This also contains the basics of a Travis CI file for automated testing and compilation.
Fixes #17 
Fixes #13 (uses `npm run make` to generate programs, this is the default name for electron but can be changed later)

2019-05-02 01:19 UTC, atruskie requested changes
The Travis build was failing, but I see you've fixed it in the meantime 👍

2019-05-02 01:19 UTC, atruskie commented on .travis.yml
> +  - os: windows
what is this `os` env variable about?

2019-05-02 01:19 UTC, atruskie commented on README.md
> +- To package the application you will need to install wine [link](https://wiki.winehq.org/Download)
what is wine needed for?

2019-05-02 01:19 UTC, atruskie commented on package.json
> +  "author": "Queensland University of Technology",
```suggestion
  "author": "QUT Ecoacoustics",
```

You should add yourself to the contributors field

2019-05-02 01:19 UTC, atruskie commented on package.json
> +        "authors": "Queensland University of Technology"
```suggestion
        "authors": "QUT Ecoacoustics"
```

2019-05-02 01:19 UTC, atruskie commented on res/qut logo.svg
> +<?xml version="1.0" encoding="utf-8"?>
Please remove this file. It violates brand guidelines, and further, we need written permission to customize it.

2019-05-02 01:19 UTC, atruskie commented on src/index.js
> +    icon: path.join(__dirname, "res/qut-logo-64.png")
fix when removing logo

2019-05-02 01:21 UTC, atruskie commented
Also, you'll need to get the build to actually pass! https://travis-ci.org/QutEcoacoustics/ap-desktop

2019-05-02 09:36 UTC, Allcharles commented
Still has the issue with the system downloading AP resulting in a API key overload. I will fix later

2019-05-07 23:44 UTC, atruskie reviewed
this token needs to be encrypted in the travis yaml and referenced here as an environment variable

2019-05-10 05:45 UTC, atruskie approved these changes

2019-05-10 05:51 UTC, merged